version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    ports: ['9200:9200']
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.1.2
    container_name: filebeat
    environment:
      - "ELASTIC_PASSWORD=elastic"
    user: root
    volumes:
      - './var/filebeat/docker.sock:/var/run/docker.sock'
      - './var/logs/:/var/lib/docker/containers/logs:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - './etc/filebeat:/usr/share/filebeat:ro'
    command: ["--strict.perms=false"]

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.1.2
  #   container_name: kibana
  #   environment:
  #     - "ELASTIC_PASSWORD=elastic"
  #   ports: ['5601:5601']
  #   volumes:
  #     - ./etc/kibana/:/usr/share/kibana/config/
  #   depends_on:
  #     - elasticsearch
