version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    ports: ['9200:9200']
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './var/elasticsearch/data:/usr/share/elasticsearch/data'

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    container_name: filebeat
    environment:
      - "ELASTIC_PASSWORD=elastic"
    user: root
    entrypoint: bash -c 'export PATH=$PATH:/usr/share/filebeat && /usr/local/bin/docker-entrypoint -e'
    volumes:
      - './var/filebeat/log/:/var/log/:ro'
      - './var/filebeat/docker.sock:/var/run/docker.sock'
      - './var/logs/:/var/lib/docker/containers/logs:ro'
    command: ["--strict.perms=false"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: ['5601:5601']
    depends_on:
      - elasticsearch
